### ISSUE TITLE
Updating the Colors

### ISSUE THREAD

**Issue by metasidd** [lilingxi01/radix-colors-swift#3]
Hey, @lilingxi01 this little repo is quite amazing. Since your last release on ~Jan 6, there seem to have been some good releases on contrast ratios and new palettes. Any appetite to update this radix swift library? 

https://www.radix-ui.com/colors/docs/overview/releases

Best,
Siddhant

**Comment by metasidd** [comment]
Here's the PR: 
https://github.com/lilingxi01/radix-colors-swift/pull/4

**Comment by lilingxi01** [comment]
Thank you for contributing!
